version: '3'
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: password
    networks:
      - app-network
  php-fpm:
    image: php:fpm-alpine3.7
    networks:
      - app-network
  nginx:
    image: nginx:latest
    ports:
      - 8002:80
    depends_on:
      - mariadb
      - php-fpm
    networks:
      - app-network
networks:
  app-network:
      driver: bridge

